version: "3.8"

services:
  database:
    image: postgres:12
    container_name: postgres-db
    environment:
      - POSTGRES_DB=osteopath
      - POSTGRES_PASSWORD=root
    ports:
      - "5432:5432"
