export type Card = {
  id: number;
  creationDate: string;
  modificationDate: string;
  age: number;
  isCastrated: boolean;
  diet: string;
  score: number;
  discipline: string;
  lifestyle: string;
  antecedent: string;
  dewormer: string;
  vaccine: string;
  marshal: string;
  dentistry: string;
  observation: string;
  schemaFilename: string;
  conclusion: string;
  treatment: string;
  restTime: string;
  activityRetake: string;
};
