export const data = {
  clients: [
    {
      id: 1,
      firstname: "Catherine",
      lastname: "Enjolras",
      email: "catherine@gmail.com",
      phone: "0606060606",
      address: "44 rue du faubourg du Nord\n34130 MAUGUIO",
      userId: 1,
      animals: [
        {
          id: 1,
          name: "Hindy",
          type: "Chien",
          subtype: null,
          sex: "Femelle",
          breed: "Bichon maltais",
          ownerId: 1,
        },
      ],
    },
    {
      id: 1,
      firstname: "Catherine",
      lastname: "Enjolras",
      email: "catherine@gmail.com",
      phone: "0606060606",
      address: "44 rue du faubourg du Nord\n34130 MAUGUIO",
      userId: 1,
      animals: [
        {
          id: 1,
          name: "Hindy",
          type: "Chien",
          subtype: null,
          sex: "Femelle",
          breed: "Bichon maltais",
          ownerId: 1,
        },
      ],
    },
    {
      id: 1,
      firstname: "Catherine",
      lastname: "Enjolras",
      email: "catherine@gmail.com",
      phone: "0606060606",
      address: "44 rue du faubourg du Nord\n34130 MAUGUIO",
      userId: 1,
      animals: [
        {
          id: 1,
          name: "Hindy",
          type: "Chien",
          subtype: null,
          sex: "Femelle",
          breed: "Bichon maltais",
          ownerId: 1,
        },
      ],
    },
    {
      id: 1,
      firstname: "Catherine",
      lastname: "Enjolras",
      email: "catherine@gmail.com",
      phone: "0606060606",
      address: "44 rue du faubourg du Nord\n34130 MAUGUIO",
      userId: 1,
      animals: [
        {
          id: 1,
          name: "Hindy",
          type: "Chien",
          subtype: null,
          sex: "Femelle",
          breed: "Bichon maltais",
          ownerId: 1,
        },
      ],
    },
  ],
};
